blank_issues_enabled: false
contact_links:
  - name: UnQOps related issues
    url: https://github.com/stackblitz/unqops.new/issues/new/choose
    about: Report issues related to UnQOps (not UnQOps)
  - name: Chat
    url: https://thinktank.ottomator.ai
    about: Ask questions and discuss with other UnQOps users.
